@echo off
rem =====================================================================
rem  Peak Works build script.
rem
rem      tools\build.bat <model> [borland-root]
rem
rem  e.g. tools\build.bat gc323
rem       tools\build.bat gc301 C:\BORLANDC
rem
rem  <model> must match a file in config\ - gc323 -> config\gc323.h.
rem  The version comes from the VERSION file. Neither the model settings
rem  nor the version is ever edited by hand before a build; that is the
rem  whole point of this script.
rem
rem  It writes two generated headers into src\ and then builds:
rem      config\<model>.h  ->  src\MODELCFG.H   (included by INTERNAL.H)
rem      VERSION           ->  src\VERSION.H    (included by ABOUT.CPP)
rem  Both are in .gitignore. Do not commit them and do not edit them.
rem
rem  Output goes to build\<model>-<version>\.
rem  The EXE keeps the name WPEAK.EXE on purpose: Windows names the
rem  settings file after the EXE, so renaming builds to jw_v16.EXE and
rem  jw_20.EXE is exactly how we ended up with JW_V16.ini, JW_20.ini and
rem  QAGC32~1.ini each holding a different flow calibration. The
rem  directory carries the identity, the file name stays stable.
rem
rem  Needs cmd.exe (Windows NT/2000/XP and later). It will not run under
rem  the Windows 9x command.com.
rem =====================================================================

setlocal

if "%~1"=="" goto usage

set MODEL=%~1
set ROOT=%~dp0..
set SRC=%ROOT%\src
set CFG=%ROOT%\config\%MODEL%.h

set BCROOT=%~2
if "%BCROOT%"=="" set BCROOT=D:\BORLANDC

if not exist "%CFG%" goto nomodel

rem ---- the version for this model, read from VERSION -------------------
set VER=
for /f "usebackq eol=# tokens=1,2 delims==" %%a in ("%ROOT%\VERSION") do (
  if /i "%%a"=="%MODEL%" set VER=%%b
)
if "%VER%"=="" goto noversion

set VMAJ=
set VMIN=
set VPAT=
for /f "tokens=1,2,3 delims=." %%a in ("%VER%") do (
  set VMAJ=%%a
  set VMIN=%%b
  set VPAT=%%c
)
if "%VPAT%"=="" goto badversion

echo.
echo Peak Works - building %MODEL% %VER%
echo.

rem ---- a change of model or version means a full rebuild ---------------
rem Half the objects compiled against another model's switches would link
rem without complaint and behave unpredictably in the field.
set STAMP=%MODEL% %VER%
set OLDSTAMP=
if exist "%SRC%\BUILD.STAMP" for /f "usebackq delims=" %%s in ("%SRC%\BUILD.STAMP") do set OLDSTAMP=%%s
if not "%STAMP%"=="%OLDSTAMP%" (
  echo   configuration changed since the last build - cleaning
  if exist "%SRC%\BUILD.STAMP" del /q "%SRC%\BUILD.STAMP"
  del /q "%SRC%\*.obj"      2>nul
  del /q "%SRC%\wpeak.res"  2>nul
  del /q "%SRC%\wpeak.sym"  2>nul
  del /q "%SRC%\WPEAK.EXE"  2>nul
)

rem ---- generate src\MODELCFG.H ----------------------------------------
echo   config\%MODEL%.h  -^>  src\MODELCFG.H
> "%SRC%\MODELCFG.H" echo /* GENERATED by tools\build.bat. Do not edit. Do not commit. */
>>"%SRC%\MODELCFG.H" echo /* Source: config\%MODEL%.h */
type "%CFG%" >> "%SRC%\MODELCFG.H"

rem ---- generate src\VERSION.H ------------------------------------------
echo   VERSION           -^>  src\VERSION.H
> "%SRC%\VERSION.H" echo /* GENERATED by tools\build.bat. Do not edit. Do not commit. */
>>"%SRC%\VERSION.H" echo /* Source: VERSION, line %MODEL%=%VER% */
>>"%SRC%\VERSION.H" echo #ifndef _PW_VERSION_H
>>"%SRC%\VERSION.H" echo #define _PW_VERSION_H 1
>>"%SRC%\VERSION.H" echo #define PW_VERSION_MAJOR %VMAJ%
>>"%SRC%\VERSION.H" echo #define PW_VERSION_MINOR %VMIN%
>>"%SRC%\VERSION.H" echo #define PW_VERSION_PATCH %VPAT%
>>"%SRC%\VERSION.H" echo #define PW_VERSION_STR "%VER%"
>>"%SRC%\VERSION.H" echo #endif

rem ---- toolchain -------------------------------------------------------
rem Same setup BC.BAT used to do by hand: S: mapped to the Borland root,
rem S:\BIN on the path, LIB and INCLUDE cleared so the compiler uses the
rem project's own settings and not whatever is in the environment.
if not exist "%BCROOT%\BIN" goto nobc
subst S: /D >nul 2>&1
subst S: "%BCROOT%" >nul 2>&1
if errorlevel 1 goto nosubst
set PATH=S:\BIN;%PATH%
set LIB=
set INCLUDE=
if not exist C:\TEMP mkdir C:\TEMP
set TMP=C:\TEMP
set TEMP=C:\TEMP

cd /d "%SRC%"

rem PRJ2MAK turns the IDE project into a makefile so the build can run
rem unattended. If this Borland install does not have it, fall back to
rem opening the project in the IDE - same as the old BC.BAT.
if not exist "S:\BIN\PRJ2MAK.EXE" goto ide

echo   PRJ2MAK WPEAK.PRJ
S:\BIN\PRJ2MAK.EXE WPEAK.PRJ WPEAK.MAK
if errorlevel 1 goto failed

echo   MAKE -f WPEAK.MAK
S:\BIN\MAKE.EXE -f WPEAK.MAK
if errorlevel 1 goto failed
goto collect

:ide
echo.
echo   PRJ2MAK.EXE was not found under %BCROOT%\BIN.
echo   Opening WPEAK.PRJ in the IDE instead - press F9 to build, then
echo   close the IDE and this script will collect the output.
echo.
S:\BIN\BC.EXE WPEAK.PRJ

:collect
if not exist "%SRC%\WPEAK.EXE" goto nooutput

set OUT=%ROOT%\build\%MODEL%-%VER%
if not exist "%ROOT%\build" mkdir "%ROOT%\build"
if not exist "%OUT%" mkdir "%OUT%"
copy /y "%SRC%\WPEAK.EXE" "%OUT%\WPEAK.EXE" >nul
if exist "%SRC%\WPEAK.HLP" copy /y "%SRC%\WPEAK.HLP" "%OUT%\WPEAK.HLP" >nul
if exist "%SRC%\WPEAK.CNT" copy /y "%SRC%\WPEAK.CNT" "%OUT%\WPEAK.CNT" >nul
> "%OUT%\BUILD.TXT" echo model=%MODEL%
>>"%OUT%\BUILD.TXT" echo version=%VER%
>>"%OUT%\BUILD.TXT" echo config=config\%MODEL%.h
>>"%OUT%\BUILD.TXT" echo date=%DATE% %TIME%

> "%SRC%\BUILD.STAMP" echo %STAMP%

echo.
echo Built %MODEL% %VER%  ->  build\%MODEL%-%VER%\WPEAK.EXE
echo Check the About box reads "%MODEL% %VER%" before you ship it.
echo.
goto end

rem ---------------------------------------------------------------------
:usage
echo.
echo Usage: tools\build.bat ^<model^> [borland-root]
echo.
echo Models:
for %%f in ("%~dp0..\config\*.h") do echo    %%~nf
echo.
goto end

:nomodel
echo ERROR: no config\%MODEL%.h - run tools\build.bat with no arguments
echo        to see the models that exist.
goto end

:noversion
echo ERROR: VERSION has no line for "%MODEL%".
echo        Add "%MODEL%=1.0.0" to VERSION and commit it.
goto end

:badversion
echo ERROR: version "%VER%" for %MODEL% is not major.minor.patch.
goto end

:nobc
echo ERROR: no Borland install at %BCROOT%.
echo        Pass the right root: tools\build.bat %MODEL% C:\BORLANDC
goto end

:nosubst
echo ERROR: could not map S: to %BCROOT%. Is S: already in use?
goto end

:failed
echo.
echo BUILD FAILED - nothing was copied to build\.
goto end

:nooutput
echo.
echo ERROR: the build produced no src\WPEAK.EXE.
goto end

:end
endlocal
